<?php /** @var \DNAFactory\GoogleTagManager\Block\Gtm $block */ ?>
<?php if ($block->isGoogleTagManagerActive()) : ?>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?= $block->getGoogleTagManagerAccount() ?>"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
<?php endif; ?>
